name: Daily GeoJSON Update

on:
  schedule:
    - cron: '0 11 * * *'   # Every day at 14:00 Israel
  workflow_dispatch:      # Optional: manual trigger from GitHub

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python update_geojson_in_looker.py

      - name: Commit and push if there are changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add all_plot.json
          git commit -m "Daily update: $(date -u)" || echo "No changes to commit"
          git push
